const CELL_PROPERTIES = {
  2: { label: '[Bl+1]', type: 'blood', value: 1, color: '#3498db' },
  3: { label: '[FF+2]', type: 'fastforward', value: 2, color: '#27ae60' },
  4: { label: '[BB+1]', type: 'bomb', value: 1, color: '#9b59b6' },
  5: { label: '[FF+5]', type: 'fastforward', value: 5, color: '#27ae60' },
  7: { label: '[FF×]', type: 'fastforward_re_roll', value: 0, color: '#2ecc71' },
  8: { label: '[UND×2]', type: 'undie', value: 2, color: '#1abc9c' },
  9: { label: '[DDD]', type: 'diediedie', value: 0, color: '#000000' },
  10: { label: '[TO→20]', type: 'goto', value: 20, color: '#f39c12' },
  11: { label: '[CR]', type: 'changeorder', value: 0, color: '#e91e63' },
  13: { label: '[FL+1]', type: 'flash', value: 1, color: '#00bcd4' },
  16: { label: '[FLB×]', type: 'flashback', value: 0, color: '#607d8b' },
  17: { label: '[FB-2]', type: 'fastback', value: 2, color: '#795548' },
  19: { label: '[BH#1]', type: 'blackhole', value: 1, color: '#212121' },
  23: { label: '[FB-3]', type: 'fastback', value: 3, color: '#795548' },
  25: { label: '[BB+2]', type: 'bomb', value: 2, color: '#9b59b6' },
  26: { label: '[BH#6]', type: 'blackhole', value: 6, color: '#212121' },
  27: { label: '[BB+1]', type: 'bomb', value: 1, color: '#9b59b6' },
  30: { label: '[Bl+1]', type: 'blood', value: 1, color: '#3498db' },
  35: { label: '[FF+3]', type: 'fastforward', value: 3, color: '#27ae60' },
  38: { label: '[FB-5]', type: 'fastback', value: 5, color: '#795548' },  
  40: { label: '[Bl-1]', type: 'blood', value: -1, color: '#e74d3c9a' },
  45: { label: '[P+2]', type: 'pause', value: 2, color: '#f39c12' },
  50: { label: '[BB+1]', type: 'bomb', value: 1, color: '#9b59b6' },
  55: { label: '[DDD]', type: 'diediedie', value: 0, color: '#000000' },
  60: { label: '[Bl+1][FF+2]', type: 'combo', properties: [{ type: 'blood', value: 1 }, { type: 'fastforward', value: 2 }], color: '#e74c3c' },
  62: { label: '[FB-5]', type: 'fastback', value: 5, color: '#795548' }
};

const PROPERTY_CONFIG = {
  blood: { name: '血液', icon: '❤️', bgColor: '#ffebee', description: 'Bl+1：血量+1，Bl-1：血量-1' , hdLabel:'block', bgImage: '../assets/ico-cell-bl.png'},
  fastforward: { name: '加速', icon: '⚡', bgColor: '#e8f5e9', description: 'FF+N：额外前进N步' },
  fastforward_re_roll: { name: '重掷加速', icon: '🔄', bgColor: '#dcedc8', description: 'FF×：再次掷骰子并前进相应步数' },
  diediedie: { name: '死亡', icon: '💀', bgColor: '#333', description: 'DDD：直接死亡' , bgImage: '../assets/ico-cell-ddd.png' },
  pause: { name: '暂停', icon: '⏸️', bgColor: '#fff3e0', description: 'P+N：暂停N回合' },
  bomb: { name: '炸弹', icon: '💣', bgColor: '#fce4ec', description: 'BB+N：以当前格子为中心，前后N格内所有玩家受伤' },
  goto: { name: '传送', icon: '🌀', bgColor: '#fff3e0', description: 'TO→N：直接传送到第N格' },
  fastback: { name: '后退', icon: '⬅️', bgColor: '#d7ccc8', description: 'FB-N：向后退N步' },
  undie: { name: '不死', icon: '🛡️', bgColor: '#e0f7fa', description: 'UND×N：N回合内不会死亡' },
  flash: { name: '闪现', icon: '✨', bgColor: '#e1f5fe', description: 'FL+N：掷骰子并前进，可连续触发' },
  flashback: { name: '回溯', icon: '🔮', bgColor: '#eceff1', description: 'FLB×：对手掷骰子后，当前玩家往回走相应步数' },
  changeorder: { name: '换序', icon: '🔀', bgColor: '#fce4ec', description: 'CR：改变玩家掷骰子的顺序' },
  blackhole: { name: '黑洞', icon: '🕳️', bgColor: '#212121', description: 'BH#N：与对应编号黑洞互换位置' },
  combo: { name: '组合', icon: '✨', bgColor: '#f3e5f5', description: '触发多个效果' }
};
